/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorRegistrar;
import controlador.ManejadorSalir;
import controlador.ManejadorVentanaP;
import main.Main;

/**
 *
 * @author tati
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ManejadorVentanaP manejadorV = new ManejadorVentanaP();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        itemRegistro.setActionCommand("itemRegistro");
        itemModificar.setActionCommand("itemModificar");
        itemEliminar.setActionCommand("itemEliminar");
        itemAsignar.setActionCommand("itemAsignar");
        itemConsultar.setActionCommand("itemConsultar");
        itemSalir.setActionCommand("itemSalir");
        
        itemSalir.addActionListener(new ManejadorSalir());
        itemRegistro.addActionListener(new ManejadorVentanaP());
        itemAsignar.addActionListener(new ManejadorVentanaP());
        itemModificar.addActionListener(new ManejadorVentanaP());
        itemEliminar.addActionListener(new ManejadorVentanaP());
        itemConsultar.addActionListener(new ManejadorVentanaP());
        
    }

    public void salir() {
        System.exit(0);
    }
    
    public void llamarVentana(int i) {
        switch (i) {
            case 1:
                Main.v.setVisible(false);
                Main.ventanaR.setVisible(true);
                break;
            case 2:
                Main.v.setVisible(false);
                Main.ventanaM.setVisible(true);
                break;
            case 3:

                Main.v.setVisible(false);
                Main.ventanaE.setVisible(true);
                break;
            case 4:

                Main.v.setVisible(false);
                Main.ventanaA.setVisible(true);
                break;
            case 5:

                Main.v.setVisible(false);
                Main.ventanaC.setVisible(true);
                break;
            default:

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelGlue = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemRegistro = new javax.swing.JMenuItem();
        itemModificar = new javax.swing.JMenuItem();
        itemEliminar = new javax.swing.JMenuItem();
        itemAsignar = new javax.swing.JMenuItem();
        itemConsultar = new javax.swing.JMenuItem();
        itemXML = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        itemJson = new javax.swing.JMenuItem();
        txt = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGlue.setBackground(new java.awt.Color(72, 184, 75));

        javax.swing.GroupLayout panelGlueLayout = new javax.swing.GroupLayout(panelGlue);
        panelGlue.setLayout(panelGlueLayout);
        panelGlueLayout.setHorizontalGroup(
            panelGlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        panelGlueLayout.setVerticalGroup(
            panelGlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        itemRegistro.setText("Registro cursos");
        itemRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistroActionPerformed(evt);
            }
        });
        jMenu1.add(itemRegistro);

        itemModificar.setText("Modificar curso");
        itemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarActionPerformed(evt);
            }
        });
        jMenu1.add(itemModificar);

        itemEliminar.setText("Eliminar curso");
        itemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(itemEliminar);

        itemAsignar.setText("Asignar estudiante a curso");
        itemAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsignarActionPerformed(evt);
            }
        });
        jMenu1.add(itemAsignar);

        itemConsultar.setText("Consultar cursos");
        itemConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(itemConsultar);

        jMenuBar1.add(jMenu1);

        itemXML.setText("Guardar");

        jMenuItem6.setText("XML");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        itemXML.add(jMenuItem6);

        itemJson.setText("Json");
        itemXML.add(itemJson);

        txt.setText("txt");
        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        itemXML.add(txt);

        jMenuBar1.add(itemXML);

        salir.setText("Salir");

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        salir.add(itemSalir);

        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEliminarActionPerformed

    private void itemAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAsignarActionPerformed

    private void itemConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemConsultarActionPerformed

    private void itemRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRegistroActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void itemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemModificarActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAsignar;
    private javax.swing.JMenuItem itemConsultar;
    private javax.swing.JMenuItem itemEliminar;
    private javax.swing.JMenuItem itemJson;
    private javax.swing.JMenuItem itemModificar;
    private javax.swing.JMenuItem itemRegistro;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu itemXML;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel panelGlue;
    private javax.swing.JMenu salir;
    private javax.swing.JMenuItem txt;
    // End of variables declaration//GEN-END:variables
}
